[package]
name = "rv"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8"
serde = {version = "1", features = ["derive"]}
reqwest = {version = "0.11", features = ["blocking"]}

[dev-dependencies]
insta = "1"
mockito = "1.0"