[package]
name = "rv"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8"
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
reqwest = { version = "0.11", features = ["blocking"] }
os_info = "3.0"
xdg = "2.5.2"

[dev-dependencies]
insta = "1"