[package]
name = "rv"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8"
serde = {version = "1", features = ["derive"]}
reqwest = { version = "0.12", features = ["blocking"] }
regex = "1"
base64 = "0.22"
cachedir = "0.3"
fs-err = "3"
etcetera = "0.8.0"
os_info = "3.9.1"

clap = {version = "4" , features = ["derive"], optional = true}
rayon = {version = "1" , optional = true}
bincode = "1"
<<<<<<< HEAD
flate2 = "1.0.35"
tar = "0.4.43"
shellexpand = "3.1.0"
=======
>>>>>>> efece0eed19ecaf1d518883e90a434f3b6182a6d

[features]
cli = ["dep:clap", "dep:rayon"]

[dev-dependencies]
insta = "1"
mockito = "1.0"

[[bin]]
name = "rv"
required-features = ["cli"]
