[package]
name = "rv"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8"
serde = {version = "1", features = ["derive"]}
reqwest = { version = "0.12", features = ["blocking"] }
regex = "1"
base64 = "0.22"
cachedir = "0.3"
fs-err = "3"
etcetera = "0.8.0"
os_info = "3.9.1"

clap = { version = "4", features = ["derive"]}
rayon = { version = "1" }
bincode = "1"
flate2 = "1.0.35"
tar = "0.4.43"
shellexpand = "3.1.0"
crossbeam-channel = "0.5.14"
rand = "0.8.5"
tempfile = "3.14.0"
url = "2.5.4"
log = "0.4.22"
env_logger = "0.11.6"

[dev-dependencies]
insta = "1"
mockito = "1.0"

[[bin]]
name = "rv"
