[package]
name = "rv"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8"
serde = {version = "1", features = ["derive"]}
reqwest = {version = "0.11", features = ["blocking"]}
regex = "1"
base64 = "0.22"
cachedir = "0.3"
fs-err = "3"
directories = "5"

clap = {version = "4" , features = ["derive"], optional = true}

[features]
cli = ["dep:clap"]

[dev-dependencies]
insta = "1"
mockito = "1.0"

[[bin]]
name = "rv"
required-features = ["cli"]
