this config was migrated from src/tests/renv/renv.lock on 2025-02-07 20:54:37
[project]
name = src/tests/renv
r_version = 4.4.1

repositories = [
    alias = "slurmtools", url = "https://a2-ai.github.io/gh-pkg-mirror/slurmtools",
    alias = "RSPM", url = "https://packagemanager.posit.co/cran/2024-12-04"
]

dependencies = [
    {name = "slurmtools", alias = "slurmtools"},
    {name = "R6", alias = "RSPM"},
    {name = "ghqc", git = "https://github.com/a2-ai/ghqc", sha = "55c23eb6a444542dab742d3d37c7b65af7b12e38"},
    {name = "rv.git.pkgA", path = "src/tests/renv/rv.git.pkgA_0.0.0.9000.tar.gz"}
]
