# Test that local source directory package installs properly
# Contains dummy.rdx in rv/library to test error case when installing from local 
# where any <package name>.rdx in the directory would trigger `rv` to consider the package to be binary
[project]
name = "simple"
r_version = "4.4"
repositories = [
    {alias = "posit", url = "https://packagemanager.posit.co/cran/2024-12-16/"}
]
dependencies = [
    { name = "dummy", path = "../../dummy-pkg/" }
]