[project]
name = "force_options"
repositories = [
    { alias = "ppm", url = "https://packagemanager.posit.co/cran/2024-03-01/" } # For first install
    # { alias  = "ppm", url = "https://packagemanager.posit.co/cran/2025-01-01/" } # For second install
]
dependencies = [
    "ggplot2"
]