# NOTE: This config should fail to resolve since there is no resolvable version available for rv.git.pkgA

[project]
name = "explicit-dep"
r_version = "4.4"

repositories = [
    { alias = "rv-test-repo1", url = "https://a2-ai.github.io/rv-test-repo/repo1" },
    { alias = "rv-test-repo2", url = "https://a2-ai.github.io/rv-test-repo/repo2" }
]

dependencies = [
    "rv.git.pkgD", # This package has a dependency constraint of rv.git.pkgA >= 0.0.5
    { name = "rv.git.pkgA", repository = "rv-test-repo2" }, # only 0.0.4 is available in repo2
]