# Compare renv.lock files generated by renv::snapshot() vs rv renv lock
# Run from e2e/ directory

renv_lock <- jsonlite::fromJSON("renv_baseline/renv.lock", simplifyVector = FALSE)
rv_lock <- jsonlite::fromJSON("rv_equivalent/renv.lock", simplifyVector = FALSE)

cat("=== R Section Comparison ===\n")
cat(sprintf("  renv R version: %s\n", renv_lock$R$Version))
cat(sprintf("  rv R version:   %s\n", rv_lock$R$Version))
cat(sprintf("  renv repos: %s\n", jsonlite::toJSON(renv_lock$R$Repositories, auto_unbox = TRUE)))
cat(sprintf("  rv repos:   %s\n", jsonlite::toJSON(rv_lock$R$Repositories, auto_unbox = TRUE)))

cat("\n=== Package Coverage ===\n")
renv_pkgs <- names(renv_lock$Packages)
rv_pkgs <- names(rv_lock$Packages)
cat(sprintf("  Only in renv (%d): %s\n", length(setdiff(renv_pkgs, rv_pkgs)), paste(setdiff(renv_pkgs, rv_pkgs), collapse = ", ")))
cat(sprintf("  Only in rv (%d): %s\n", length(setdiff(rv_pkgs, renv_pkgs)), paste(setdiff(rv_pkgs, renv_pkgs), collapse = ", ")))
cat(sprintf("  In both (%d): %s\n", length(intersect(renv_pkgs, rv_pkgs)), paste(intersect(renv_pkgs, rv_pkgs), collapse = ", ")))

cat("\n=== Per-Package Field Comparison ===\n")
shared_pkgs <- intersect(renv_pkgs, rv_pkgs)
for (pkg in sort(shared_pkgs)) {
  renv_pkg <- renv_lock$Packages[[pkg]]
  rv_pkg <- rv_lock$Packages[[pkg]]
  all_keys <- sort(unique(c(names(renv_pkg), names(rv_pkg))))

  diffs <- list()
  matches <- character()
  for (key in all_keys) {
    renv_val <- renv_pkg[[key]]
    rv_val <- rv_pkg[[key]]
    if (identical(renv_val, rv_val)) {
      matches <- c(matches, key)
    } else {
      diffs[[key]] <- list(renv = renv_val, rv = rv_val)
    }
  }

  if (length(diffs) == 0) {
    cat(sprintf("\n--- %s: IDENTICAL (%d fields) ---\n", pkg, length(matches)))
  } else {
    cat(sprintf("\n--- %s: %d match, %d differ ---\n", pkg, length(matches), length(diffs)))
    cat(sprintf("  Matching: %s\n", paste(matches, collapse = ", ")))
    for (key in names(diffs)) {
      d <- diffs[[key]]
      renv_str <- if (is.null(d$renv)) "(absent)" else jsonlite::toJSON(d$renv, auto_unbox = TRUE)
      rv_str <- if (is.null(d$rv)) "(absent)" else jsonlite::toJSON(d$rv, auto_unbox = TRUE)
      cat(sprintf("  DIFF %s:\n    renv: %s\n    rv:   %s\n", key, renv_str, rv_str))
    }
  }
}
