//! Generates a bioc data table that gets included in rv so we can derive the right versions
//! to use given a specific R.

use std::collections::HashMap;
use std::path::Path;
use std::str::FromStr;

use rv::Version;
use serde::Deserialize;

const BIOC_CONFIG_URL: &str = "https://bioconductor.org/config.yaml";

#[derive(Debug, Deserialize)]
struct Config {
    release_version: String,
    devel_version: String,
    r_ver_for_bioc_ver: HashMap<String, String>,
}

fn main() {
    let mut resp = ureq::get(BIOC_CONFIG_URL)
        .call()
        .expect("failed to get bioc config");
    let yaml_content = resp
        .body_mut()
        .read_to_string()
        .expect("failed to read bioc config");
    let config: Config = yaml_serde::from_str(&yaml_content).expect("failed to parse config");

    let mut versions = HashMap::new();

    for (bioc_version, r_version) in config.r_ver_for_bioc_ver {
        versions
            .entry(bioc_version)
            .or_insert_with(Vec::new)
            .push(Version::from_str(&r_version).expect("Invalid R version"));
    }

    let mut versions: Vec<_> = versions.into_iter().collect();
    // Sort by parsed version so the table reads chronologically
    versions.sort_by_key(|(bioc, _)| Version::from_str(bioc).expect("Invalid bioc version"));

    let mut rows = String::new();
    let count = versions.len();
    for (bioc_version, r_versions) in versions {
        for r in r_versions {
            let major_minor = r.major_minor();
            rows.push_str(&format!(r#"({bioc_version:?}, {major_minor:?}),"#));
            rows.push('\n');
        }
    }

    // it will be cargo fmt later
    let table_file = format!(
        r#"
//! Generated by `just bioc`
pub const BIOC_VERSION_MAP: [(&str, [u32; 2]); {count}] = [
{rows}
];

pub const BIOC_DEVEL: &str = "{}";
pub const BIOC_CURRENT_RELEASE: &str = "{}";
"#,
        config.devel_version, config.release_version
    );

    let path = Path::new(".").join("src").join("bioc.rs");
    std::fs::write(&path, table_file).expect("failed to write table");
}
