[project]
name = "git typo"
r_version = "4.5"

repositories = [
    # repo contains rv.git.pkgA and rv.git.pkgD
    { alias = "rv-test-repo", url = "https://a2-ai.github.io/rv-test-repo/repo1" },
]

dependencies = [
    # typo on rv.git.pkgA's git repo
    { name = "rv.git.pkgA", git = "https://github.com/a2-ai/rv.git.typo", branch = "main" },
    # depends on rv.git.pkgA
    "rv.git.pkgD",
]
