[project]
name = "multi-repo"
repositories = [
    { alias = "scicalc", url = "https://a2-ai.github.io/gh-pkg-mirror/scicalc/" },
    { alias = "a2-ai", url = "https://packagemanager.posit.co/cran/2024-12-22/" }
]
dependencies = [
    "scicalc"
]