[project]
name = "multi-repo"
r_version = "4.4"
repositories = [
    { alias = "scicalc", url = "https://a2-ai.github.io/gh-pkg-mirror/scicalc/" },
    { alias = "a2-ai", url = "https://a2-ai.github.io/rv-test-snapshot/2024-12-22/" }
]
dependencies = [
    "scicalc"
]
