[project]
name = "simple"
repositories = [
    {alias = "posit-new", url = "https://packagemanager.posit.co/cran/2025-01-10/"},
    {alias = "posit-old", url = "https://packagemanager.posit.co/cran/2024-03-01/"},
]

dependencies = [
    {name = "ggplot2", repository = "posit-new"},
    {name = "usethis", repository = "posit-old"},
]