[project]
name = "git-dep"
r_version = "4.4"
repositories = [
    {alias = "posit", url = "https://packagemanager.posit.co/cran/2024-12-16/"}
]
dependencies = [
    # This one has a git remote for a dep
    { name = "gsm", git = "https://github.com/Gilead-BioStats/gsm/", tag ="v2.2.2", install_suggestions = true},
]
