[project]
name = "git-dep"
r_version = "4.4"
repositories = [
    {alias = "posit", url = "https://packagemanager.posit.co/cran/2024-12-16/"}
]
dependencies = [
    {name = "tomledit", git = "https://github.com/Keats/tomledit", branch = "readme"},
]
