[project]
# Note: do not update the lockfile from this project since we're testing whether an upgrade
# url is updated by 10 months to upgrade the version/source of the packages
name = "project-upgrade"
r_version = "4.4"
repositories = [
    {alias = "PPM", url = "https://packagemanager.posit.co/cran/2024-12-22"}
]

dependencies = [
    "ggplot2"
]