[project]
name = "Config/Needs test"
description = "Testing Config/Needs/* on custom package with multi-needs"
r_version = "4.5"

repositories = [
    { alias = "rv.needs.pkgA", url = "https://a2-ai.github.io/rv.needs.pkgA/0.1.0" },
    { alias = "PPM", url = "https://packagemanager.posit.co/cran/latest" },
]

dependencies = [
    { name = "rv.needs.pkgA", needs = [ "simple", "version_constraint", "multi_line", "remote_pkg" ] },
]
