[project]
name = "simple"
repositories = [
    {alias = "posit", url = "https://packagemanager.posit.co/cran/2024-12-16/"}
]
dependencies = [
    "dplyr",
   # "ggplot2"  # to be added after first run
]