name: R Integration Tests

on:
  push:
    branches: [ r-tests ]
  pull_request:
    branches: [ r-tests ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4'
        
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        
    - name: Verify R installation
      run: |
        R --version
        which R
        R --slave -e "cat('R is working:', R.version.string, '\n')"
        R --slave -e "cat('Library paths:', paste(.libPaths(), collapse=', '), '\n')"
        R --slave -e "cat('Working directory:', getwd(), '\n')"
        R --slave -e "cat('R_LIBS_USER:', Sys.getenv('R_LIBS_USER'), '\n')"
        R --slave -e "cat('R_LIBS_SITE:', Sys.getenv('R_LIBS_SITE'), '\n')"
        
    - name: Run diagnostic paths test
      run: cargo test --features=cli --test init test_diagnose_paths_workflow -- --nocapture --test-threads=1
      env:
        RUST_BACKTRACE: 1
