name: R Integration Tests

on:
  push:
    branches: [ r-tests ]
  pull_request:
    branches: [ r-tests ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4'
        
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchains: stable
        
    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Verify R installation
      run: |
        R --version
        which R
        R --slave -e "cat('R is working:', R.version.string, '\n')"
        R --slave -e "cat('Library paths:', paste(.libPaths(), collapse=', '), '\n')"
        
    - name: Build rv
      run: cargo build --features=cli --release
      
    - name: Run basic init test
      run: cargo test --features=cli test_rv_init_basic -- --nocapture
      env:
        RUST_BACKTRACE: 1
        
    - name: Run R process test
      run: cargo test --features=cli test_rv_init_with_r_process -- --nocapture
      env:
        RUST_BACKTRACE: 1
        
    - name: Run R6 workflow test
      run: cargo test --features=cli test_r6_workflow -- --nocapture
      env:
        RUST_BACKTRACE: 1
